audio_node:
  ros__parameters:
    state_topic: /lcr/audio/play
    state_map:
      emergency_stop_trigger: "sounds/emergency_stop_trigger.wav"
      emergency_stop_reset: "sounds/emergency_stop_reset.wav"
      emergency_stop_state: "sounds/emergency_stop_state.wav"
      normal_state: "sounds/normal_state.wav"
      unit_online: "sounds/unit_online.wav"
      unit_shutdown: "sounds/unit_shutdown.wav"
      control_device_disconnected: "sounds/control_device_disconnected.wav"
      control_device_connected: "sounds/control_device_connected.wav"
      hazard_toggle: "sounds/hazard_toggle.wav"
      light_mode_change: "sounds/light_mode_change.wav"
      alarm: "sounds/alarm.wav"
      alert: "sounds/alert.wav"
      red_low_power: "sounds/red_low_power.wav"
      yellow_low_power: "sounds/yellow_low_power.wav"
      lock: "sounds/lock.wav"
      success: "sounds/success.wav"
      horn: "sounds/horn.wav"
      vacuum_latch: "sounds/vacuum_latch.wav"
      vacuum_latch_time_decrease: "sounds/vacuum_latch_time_decrease.wav"
      vacuum_latch_time_increase: "sounds/vacuum_latch_time_increase.wav"
      vacuum_off_delay_decrease: "sounds/vacuum_off_delay_decrease.wav"
      vacuum_off_delay_increase: "sounds/vacuum_off_delay_increase.wav"
      unit_movement_1: "sounds/unit_movement_1.wav"
      unit_movement_2: "sounds/unit_movement_2.wav"
      unit_movement_3: "sounds/unit_movement_3.wav"
      unit_movement_4: "sounds/unit_movement_4.wav"
      unit_movement_5: "sounds/unit_movement_5.wav"
      unit_speed_1: "sounds/unit_speed_1.wav"
      unit_speed_2: "sounds/unit_speed_2.wav"
      unit_speed_3: "sounds/unit_speed_3.wav"
      unit_speed_4: "sounds/unit_speed_4.wav"
      unit_speed_5: "sounds/unit_speed_5.wav"
