# The configuration file provides values for the two, differential
# drive motors, 'm1' and 'm2'. See the article:
# https://resources.basicmicro.com/auto-tuning-with-motion-studio/
# for a description of how to derive the p, i, d and qpps values.
#
# The two strings ***motor_driver_node*** and ***ros_parameters*** must match
# the code in the launch file.

roboclaw_twist_node:
  ros__parameters:
    # Incremental acceleration to use in quadrature pulses per second.
    accel_quad_pulses_per_second: 20000

    # The device name to be opened.
    device_name: "/dev/roboclaw"

    # RoboClaw serial port baudrate
    device_baudrate: 38400

    # The assigned port for the device (as configured on the RoboClaw).
    device_address: 128

    # The P, I, D and maximum quadrature pulses per second for both motors.
    m1_p: 0.9488
    m1_i: 0.01643
    m1_d: 0.0
    m1_qpps: 204375
    m2_p: 0.09552
    m2_i: 0.01641
    m2_d: 0.0
    m2_qpps: 204375

    # The maximum expected current (in amps) for both motors.
    # A motor will be commanded to stop if it exceeds this current.
    m1_max_current: 6.3
    m2_max_current: 6.3

    # Rate limiting commands. The driver will clip any value
    # exceeding these limits.
    max_angular_velocity: 3.0
    max_linear_velocity: 3.0

    # If no new motor commands is received since the last motor
    # command in this number of seconds, stop the motors.
    max_seconds_uncommanded_travel: 0.25

    # Based upon your particular motor gearing and encoders.
    # These values are used to scale cmd_vel commands
    # and encoder values to motor commands and odometry, respectfully.
    quad_pulses_per_meter: 93616
    quad_pulses_per_revolution: 148849

    # Based upon y our particular robot model.
    # The wheel separation and radius, in meters.
    wheel_radius: 0.260
    wheel_separation: 0.54

    # Topic name to be used to publish the RoboClaw status messages.
    roboclaw_status_topic: "roboclaw_status"

    # See: http://unixwiz.net/techtips/termios-vmin-vtime.html
    vmin: 1
    vtime: 2
